version: "3"

services:
  bot:
    build: ./
    # ports: 
    volumes:
      -  ./:/home
    depends_on:
      - db
    environment:
      TOKEN:  
      HOST: db
      PORT: 3306
      USER: root
      PASSWORD: mysqlrootpassword
      admin_id: 1339488902
  db:
    build: ./db
    restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: pass    
    volumes:
      - ./db/databases:/var/lib/mysql
    ports: 
      - 3306:3306
