version: "3"

services:
  bot:
    build: ./
    # ports: 
    volumes:
      -  ./:/home
    depends_on:
      - db
    environment:
      TOKEN: token bot
      HOST: db
      PORT: 3306
      USER: root
      PASSWORD: password databases
      admin_id: admin id 
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  password databases
    volumes:
      - ./db/databases:/var/lib/mysql
    ports: 
      - 3306:3306
