version: "3"

services:
  bot:
    build: ./
    # ports: 
    volumes:
      -  ./:/home
    depends_on:
      - db
    environment:
      TOKEN: 1464338295:AAEpSAjxUh4sLCOMqjk3Sj9U9-6GeKnOgNo 
      HOST: db
      PORT: 3306
      USER: root
      PASSWORD: Fmk5WaFsLOGGzoEn
      admin_id: 1437775058
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  Fmk5WaFsLOGGzoEn  
    volumes:
      - ./db/databases:/var/lib/mysql
    ports: 
      - 3306:3306
